### ISSUE TITLE
Update column names for tutorial

### ISSUE THREAD

**Issue by apblair** [AllenInstitute/scrattch.hicat#21]
Hello!

My name is Andrew Blair, a graduate student at UCSC in Josh Stuart's lab. First, congratulations and thank you for providing a clear and descriptive tutorial!

I ran into a few minor annotation 'bugs' during the tutorial though and wanted to let you guys know:

1. Update from tutorial 'primary_type' to 'primary_type_label' and 'sample_id' to 'sample_name' 
select.cells <- tasic_2016_anno %>%
  filter(primary_type_label != "unclassified") %>%
  filter(grepl("Igtp|Ndnf|Vip|Sncg|Smad3",primary_type_label)) %>%
  select(sample_name) %>%
  unlist()

2.  The column 'primary_type' was not present in the data frame
ref.cl.df <- as.data.frame(unique(anno[,c("primary_type_id", "primary_type_color", "broad_type")]))

3. Update from anno$sample_id to anno$sample_name
ref.cl <- setNames(factor(anno$primary_type_id), anno$sample_name)

Your tutorial worked after these updates.

Thanks Again!

**Comment by hypercompetent** [comment]
Thanks, Andrew! I'll try to get these fixed soon.

-Lucas
