### ISSUE TITLE
fast_tsne.R breaks installation of dev branch

### ISSUE THREAD

**Issue by tebakken** [AllenInstitute/scrattch.hicat#25]
Warning in file(filename, "r", encoding = encoding) :
  cannot open file '/home/trygveb/src/FIt-SNE/fast_tsne.R': No such file or directory
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Error : unable to load R code in package ‘scrattch.hicat’
ERROR: lazy loading failed for package ‘scrattch.hicat’

**Comment by hypercompetent** [comment]
I'm not sure what update fixed this, but it looks like this is no longer a problem.
