### ISSUE TITLE
Plot River includes source files not included

### ISSUE THREAD

**Issue by bharris12** [AllenInstitute/scrattch.hicat#47]
The riverplot function include two lines that source code not included in the repository, when you run the function it gives this error.

In file(filename, "r", encoding = encoding) :
  cannot open file '/home/bharris/zizhen/My_R/map_river_plot.R': No such file or directory

when I view the function, it appears that both of these will throw an error
```
	source("~/zizhen/My_R/map_river_plot.R")
	source("~/zizhen/My_R/sankey_functions.R")
```

**Comment by cvanvelt** [comment]
I would suggest using the scrattch.vis package [https://github.com/AllenInstitute/scrattch.vis](url). This contains the full River_plot function. But thanks for pointing this out and we'll remove it from the next update.
