### ISSUE TITLE
How to cite scratch.hicat ?

### ISSUE THREAD

**Issue by carmensandoval** [AllenInstitute/scrattch.hicat#60]
I've used some of your code for my own research and I'm trying to find a way to reference your package. Could you please point me to the correct reference?

Thanks!

**Comment by hypercompetent** [comment]
Hi Carmen,

I recommend citing Tasic, et al. 2018, which is the first place we published the use of scrattch:
https://www.nature.com/articles/s41586-018-0654-5 

Tasic, B., Yao, Z., Graybuck, L.T. et al. Shared and distinct transcriptomic cell types across neocortical areas. Nature 563, 72–78 (2018). https://doi.org/10.1038/s41586-018-0654-5

Cheers,
-Lucas
