### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by ZhenyaoYe** [AllenInstitute/scrattch.hicat#77]
Hi,

I tried installing package, scrattch.hicat, using remotes::install_github("AllenInstitute/scrattch.hicat"), while the below error messages were obtained: 

Downloading GitHub repo AllenInstitute/scrattch.hicat@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/AllenInstitute/scrattch.hicat/tarball/HEAD' failed

Any suggestions are appreciated! 

Best regards,
Zhenyao

**Comment by mmyoung** [comment]
I also ran into this problem when installing it. Have you solved it yet?

**Comment by mmyoung** [comment]
> Are you still having issues installing hicat?

The problem has been solved, it turned out to be the network.
